### Create a realm
POST /realms/create HTTP/1.1
Host: {{event-sourcing-configurator.host}}
Content-Type: application/json

{
  "name": "demogods",
  "displayName": "Realm of the Demo Gods"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Create a client
POST /realms/demogods/clients/create HTTP/1.1
Host: {{event-sourcing-configurator.host}}
Content-Type: application/json

{
  "clientId": "godmode"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Replay events by aggregate Id
POST /replay HTTP/1.1
Host: {{event-sourcing-configurator.host}}
Content-Type: application/json

{
  "aggregateId": "demogods"
}